"""Add is_active column to User model

Revision ID: 94064932c4ca
Revises: 22aad57754cc
Create Date: 2025-05-26 02:07:47.379124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94064932c4ca'
down_revision = '22aad57754cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
